-- [nfnl] init.fnl
vim.loader.enable()
require("vim._core.ui2").enable({enable = true})
require("opts")
require("keymaps")
require("ui")
require("mini")
require("tools")
require("dev")
return require("zfc.dial")
