# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-yank'


##### Kanagawa minimal (pure rectangle) #####

# 主色
set -g @minimal-tmux-bg "#1F1F28"
set -g @minimal-tmux-fg "#DCD7BA"

# 关闭所有箭头（关键）
set -g @minimal-tmux-use-arrow false

# 状态栏位置
set -g @minimal-tmux-indicator false
set -g @minimal-tmux-status "top"

# 左右启用
set -g @minimal-tmux-left true
set -g @minimal-tmux-right true

# 左侧（session）
set -g @minimal-tmux-status-left-extra "#[bg=#2A2A37,fg=#DCD7BA] #S "

# 右侧（时间）
set -g @minimal-tmux-status-right " "
# set -g @minimal-tmux-status-right-extra "#[bg=#2A2A37,fg=#DCD7BA] %m/%d %H:%M"
set -g @minimal-tmux-status-right-extra "#[bg=#2A2A37,fg=#7E9CD8] %m/%d #[bg=#2A2A37,fg=#DCD7BA] %H:%M"

# 长度
set -g status-left-length 20
set -g status-right-length 20

##### 基础 #####
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ",xterm-256color:RGB"


##### 前缀键（更舒服）#####
unbind C-b
set -g prefix C-q
bind C-q send-prefix

##### 分屏 #####
bind s split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

##### 重载配置 #####
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

##### 窗口（tab）行为 #####
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

##### 你的快捷键 #####
# Alt+w 新建 tab
bind -n M-w new-window -c "#{pane_current_path}"

# Alt+n 下一个 tab
bind -n M-n next-window

# Alt+p 上一个 tab
bind -n M-p previous-window


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
