#!/bin/sh

notmuch tag +crypto -- 'from:coindesk.com or from:cointelegraph.com or from:binance.com or from:okx.com or from:coinbase.com'


notmuch tag +dev -- 'from:github.com or from:gitlab.com or from:codeberg.org'
