[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"

[[plugin.prepend_fetchers]]
id = "mime"
url = "local://*"
run = "mime-ext.local"
prio = "high"

[[plugin.prepend_fetchers]]
id = "mime"
url = "remote://*"
run = "mime-ext.remote"
prio = "high"

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run = "ouch"
